<a href="https://colab.research.google.com/github/CVanchieri/DS-Unit-2-Regression-Classification/blob/master/2_Assignment_RegressionClassification_Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science, Unit 2: Predictive Modeling

# Regression & Classification, Module 2

## Assignment

You'll continue to **predict how much it costs to rent an apartment in NYC,** using the dataset from renthop.com.

- [ ] Do train/test split. Use data from April & May 2016 to train. Use data from June 2016 to test.
- [ ] Engineer at least two new features. (See below for explanation & ideas.)
- [ ] Fit a linear regression model with at least two features.
- [ ] Get the model's coefficients and intercept.
- [ ] Get regression metrics RMSE, MAE, and $R^2$, for both the train and test data.
- [ ] What's the best test MAE you can get? Share your score and features used with your cohort on Slack!
- [ ] As always, commit your notebook to your fork of the GitHub repo.


#### [Feature Engineering](https://en.wikipedia.org/wiki/Feature_engineering)

> "Some machine learning projects succeed and some fail. What makes the difference? Easily the most important factor is the features used." — Pedro Domingos, ["A Few Useful Things to Know about Machine Learning"](https://homes.cs.washington.edu/~pedrod/papers/cacm12.pdf)

> "Coming up with features is difficult, time-consuming, requires expert knowledge. 'Applied machine learning' is basically feature engineering." — Andrew Ng, [Machine Learning and AI via Brain simulations](https://forum.stanford.edu/events/2011/2011slides/plenary/2011plenaryNg.pdf) 

> Feature engineering is the process of using domain knowledge of the data to create features that make machine learning algorithms work. 

#### Feature Ideas
- Does the apartment have a description?
- How long is the description?
- How many total perks does each apartment have?
- Are cats _or_ dogs allowed?
- Are cats _and_ dogs allowed?
- Total number of rooms (beds + baths)
- Ratio of beds to baths
- What's the neighborhood, based on address or latitude & longitude?

## Stretch Goals
- [ ] If you want more math, skim [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf),  Chapter 3.1, Simple Linear Regression, & Chapter 3.2, Multiple Linear Regression
- [ ] If you want more introduction, watch [Brandon Foltz, Statistics 101: Simple Linear Regression](https://www.youtube.com/watch?v=ZkjP5RJLQF4)
(20 minutes, over 1 million views)
- [ ] Do the [Plotly Dash](https://dash.plot.ly/) Tutorial, Parts 1 & 2.
- [ ] Add your own stretch goal(s) !

In [4]:
# If you're in Colab...
import os, sys
in_colab = 'google.colab' in sys.modules

if in_colab:
    # Install required python packages:
    # pandas-profiling, version >= 2.0
    # plotly, version >= 4.0
    !pip install --upgrade pandas-profiling plotly
    
    # Pull files from Github repo
    os.chdir('/content')
    !git init .
    !git remote add origin https://github.com/LambdaSchool/DS-Unit-2-Regression-Classification.git
    !git pull origin master
    
    # Change into directory for module
    os.chdir('module1')

Collecting pandas-profiling
  Downloading https://files.pythonhosted.org/packages/2c/2f/aae19e2173c10a9bb7fee5f5cad35dbe53a393960fc91abc477dcc4661e8/pandas-profiling-2.3.0.tar.gz (127kB)
     |████████████████████████████████| 133kB 4.8MB/s
Collecting plotly
  Downloading https://files.pythonhosted.org/packages/70/19/8437e22c84083a6d5d8a3c80f4edc73c9dcbb89261d07e6bd13b48752bbd/plotly-4.1.1-py2.py3-none-any.whl (7.1MB)
     |████████████████████████████████| 7.1MB 48.3MB/s
Requirement already satisfied, skipping upgrade: pandas>=0.19 in /usr/local/lib/python3.6/dist-packages (from pandas-profiling) (0.24.2)
Requirement already satisfied, skipping upgrade: matplotlib>=1.4 in /usr/local/lib/python3.6/dist-packages (from pandas-profiling) (3.0.3)
Requirement already satisfied, skipping upgrade: jinja2>=2.8 in /usr/local/lib/python3.6/dist-packages (from pandas-profiling) (2.10.1)
Requirement already satisfied, skipping upgrade: missingno>=0.4.2 in /usr/local/lib/python3.6/dist-packages (from pandas-profiling) (0.4.2)
Collecting htmlmin>=0.1.12 (from pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/b3/e7/fcd59e12169de19f0131ff2812077f964c6b960e7c09804d30a7bf2ab461/htmlmin-0.1.12.tar.gz
Collecting phik>=0.9.8 (from pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/45/ad/24a16fa4ba612fb96a3c4bb115a5b9741483f53b66d3d3afd987f20fa227/phik-0.9.8-py3-none-any.whl (606kB)
     |████████████████████████████████| 614kB 28.7MB/s
Collecting confuse>=1.0.0 (from pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/4c/6f/90e860cba937c174d8b3775729ccc6377eb91f52ad4eeb008e7252a3646d/confuse-1.0.0.tar.gz
Requirement already satisfied, skipping upgrade: astropy in /usr/local/lib/python3.6/dist-packages (from pandas-profiling) (3.0.5)
Requirement already satisfied, skipping upgrade: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly) (1.3.3)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.6/dist-packages (from plotly) (1.12.0)
Requirement already satisfied, skipping upgrade: numpy>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.19->pandas-profiling) (1.16.5)
Requirement already satisfied, skipping upgrade: pytz>=2011k in /usr/local/lib/python3.6/dist-packages (from pandas>=0.19->pandas-profiling) (2018.9)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.19->pandas-profiling) (2.5.3)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.4->pandas-profiling) (1.1.0)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.4->pandas-profiling) (0.10.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.4->pandas-profiling) (2.4.2)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2>=2.8->pandas-profiling) (1.1.1)
Requirement already satisfied, skipping upgrade: scipy in /usr/local/lib/python3.6/dist-packages (from missingno>=0.4.2->pandas-profiling) (1.3.1)
Requirement already satisfied, skipping upgrade: seaborn in /usr/local/lib/python3.6/dist-packages (from missingno>=0.4.2->pandas-profiling) (0.9.0)
Collecting pytest>=4.0.2 (from phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/2f/19/d5f71752f71451ccc5ed5f6739e9da4a235f38783fdaf3629cae41b2ca7b/pytest-5.1.2-py3-none-any.whl (224kB)
     |████████████████████████████████| 225kB 57.8MB/s
Requirement already satisfied, skipping upgrade: nbconvert>=5.3.1 in /usr/local/lib/python3.6/dist-packages (from phik>=0.9.8->pandas-profiling) (5.6.0)
Requirement already satisfied, skipping upgrade: jupyter-client>=5.2.3 in /usr/local/lib/python3.6/dist-packages (from phik>=0.9.8->pandas-profiling) (5.3.1)
Requirement already satisfied, skipping upgrade: numba>=0.38.1 in /usr/local/lib/python3.6/dist-packages (from phik>=0.9.8->pandas-profiling) (0.40.1)
Collecting pytest-pylint>=0.13.0 (from phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/64/dc/6f35f114844fb12e38d60c4f3d2441a55baff7043ad4e013777dff55746c/pytest_pylint-0.14.1-py3-none-any.whl
Requirement already satisfied, skipping upgrade: pyyaml in /usr/local/lib/python3.6/dist-packages (from confuse>=1.0.0->pandas-profiling) (3.13)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.6/dist-packages (from kiwisolver>=1.0.1->matplotlib>=1.4->pandas-profiling) (41.2.0)
Requirement already satisfied, skipping upgrade: py>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (1.8.0)
Collecting pluggy<1.0,>=0.12 (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/06/ee/de89e0582276e3551df3110088bf20844de2b0e7df2748406876cc78e021/pluggy-0.12.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (0.20)
Requirement already satisfied, skipping upgrade: more-itertools>=4.0.0 in /usr/local/lib/python3.6/dist-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (7.2.0)
Requirement already satisfied, skipping upgrade: atomicwrites>=1.0 in /usr/local/lib/python3.6/dist-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (1.3.0)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (19.1.0)
Requirement already satisfied, skipping upgrade: wcwidth in /usr/local/lib/python3.6/dist-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (0.1.7)
Requirement already satisfied, skipping upgrade: packaging in /usr/local/lib/python3.6/dist-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (19.1)
Requirement already satisfied, skipping upgrade: entrypoints>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.3)
Requirement already satisfied, skipping upgrade: bleach in /usr/local/lib/python3.6/dist-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (3.1.0)
Requirement already satisfied, skipping upgrade: traitlets>=4.2 in /usr/local/lib/python3.6/dist-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (4.3.2)
Requirement already satisfied, skipping upgrade: testpath in /usr/local/lib/python3.6/dist-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.4.2)
Requirement already satisfied, skipping upgrade: pygments in /usr/local/lib/python3.6/dist-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (2.1.3)
Requirement already satisfied, skipping upgrade: nbformat>=4.4 in /usr/local/lib/python3.6/dist-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (4.4.0)
Requirement already satisfied, skipping upgrade: pandocfilters>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (1.4.2)
Requirement already satisfied, skipping upgrade: mistune<2,>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.8.4)
Requirement already satisfied, skipping upgrade: defusedxml in /usr/local/lib/python3.6/dist-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.6.0)
Requirement already satisfied, skipping upgrade: jupyter-core in /usr/local/lib/python3.6/dist-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (4.5.0)
Requirement already satisfied, skipping upgrade: tornado>=4.1 in /usr/local/lib/python3.6/dist-packages (from jupyter-client>=5.2.3->phik>=0.9.8->pandas-profiling) (4.5.3)
Requirement already satisfied, skipping upgrade: pyzmq>=13 in /usr/local/lib/python3.6/dist-packages (from jupyter-client>=5.2.3->phik>=0.9.8->pandas-profiling) (17.0.0)
Requirement already satisfied, skipping upgrade: llvmlite>=0.25.0dev0 in /usr/local/lib/python3.6/dist-packages (from numba>=0.38.1->phik>=0.9.8->pandas-profiling) (0.29.0)
Collecting pylint>=1.4.5 (from pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/60/c2/b3f73f4ac008bef6e75bca4992f3963b3f85942e0277237721ef1c151f0d/pylint-2.3.1-py3-none-any.whl (765kB)
     |████████████████████████████████| 768kB 52.7MB/s
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (0.6.0)
Requirement already satisfied, skipping upgrade: webencodings in /usr/local/lib/python3.6/dist-packages (from bleach->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.5.1)
Requirement already satisfied, skipping upgrade: decorator in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.2->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (4.4.0)
Requirement already satisfied, skipping upgrade: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.2->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.2.0)
Requirement already satisfied, skipping upgrade: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.6/dist-packages (from nbformat>=4.4->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (2.6.0)
Collecting mccabe<0.7,>=0.6 (from pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting isort<5,>=4.2.5 (from pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl (42kB)
     |████████████████████████████████| 51kB 29.1MB/s
Collecting astroid<3,>=2.2.0 (from pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/d5/ad/7221a62a2dbce5c3b8c57fd18e1052c7331adc19b3f27f1561aa6e620db2/astroid-2.2.5-py3-none-any.whl (193kB)
     |████████████████████████████████| 194kB 63.5MB/s
Collecting typed-ast>=1.3.0; implementation_name == "cpython" (from astroid<3,>=2.2.0->pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/31/d3/9d1802c161626d0278bafb1ffb32f76b9d01e123881bbf9d91e8ccf28e18/typed_ast-1.4.0-cp36-cp36m-manylinux1_x86_64.whl (736kB)
     |████████████████████████████████| 737kB 48.6MB/s
Collecting lazy-object-proxy (from astroid<3,>=2.2.0->pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/0e/26/534a6d32572a9dbca11619321535c0a7ab34688545d9d67c2c204b9e3a3d/lazy_object_proxy-1.4.2-cp36-cp36m-manylinux1_x86_64.whl (49kB)
     |████████████████████████████████| 51kB 24.5MB/s
Requirement already satisfied, skipping upgrade: wrapt in /usr/local/lib/python3.6/dist-packages (from astroid<3,>=2.2.0->pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (1.11.2)
Building wheels for collected packages: pandas-profiling, htmlmin, confuse
  Building wheel for pandas-profiling (setup.py) ... done
  Created wheel for pandas-profiling: filename=pandas_profiling-2.3.0-py2.py3-none-any.whl size=145035 sha256=8f645d8854e669d8314eb08c6c0bd7ad1b73a6ed91e2bd7dccfc8b69e82eb288
  Stored in directory: /root/.cache/pip/wheels/ce/c7/f1/dbfef4848ebb048cb1d4a22d1ed0c62d8ff2523747235e19fe
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-cp36-none-any.whl size=27084 sha256=6a82bb7786e845256bbe3724ec8ac6082ba7aaff01fdc9e03ea555aca9d2675e
  Stored in directory: /root/.cache/pip/wheels/43/07/ac/7c5a9d708d65247ac1f94066cf1db075540b85716c30255459
  Building wheel for confuse (setup.py) ... done
  Created wheel for confuse: filename=confuse-1.0.0-cp36-none-any.whl size=17486 sha256=6b40ecc2d06cd5e5bfe79ee0a13717c58dc7e413c05fed8fa16e09d33f8068c6
  Stored in directory: /root/.cache/pip/wheels/b0/b2/96/2074eee7dbf7b7df69d004c9b6ac4e32dad04fb7666cf943bd
Successfully built pandas-profiling htmlmin confuse
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
Installing collected packages: htmlmin, pluggy, pytest, mccabe, isort, typed-ast, lazy-object-proxy, astroid, pylint, pytest-pylint, phik, confuse, pandas-profiling, plotly
  Found existing installation: pluggy 0.7.1
    Uninstalling pluggy-0.7.1:
      Successfully uninstalled pluggy-0.7.1
  Found existing installation: pytest 3.6.4
    Uninstalling pytest-3.6.4:
      Successfully uninstalled pytest-3.6.4
  Found existing installation: pandas-profiling 1.4.1
    Uninstalling pandas-profiling-1.4.1:
      Successfully uninstalled pandas-profiling-1.4.1
  Found existing installation: plotly 3.6.1
    Uninstalling plotly-3.6.1:
      Successfully uninstalled plotly-3.6.1
Successfully installed astroid-2.2.5 confuse-1.0.0 htmlmin-0.1.12 isort-4.3.21 lazy-object-proxy-1.4.2 mccabe-0.6.1 pandas-profiling-2.3.0 phik-0.9.8 plotly-4.1.1 pluggy-0.12.0 pylint-2.3.1 pytest-5.1.2 pytest-pylint-0.14.1 typed-ast-1.4.0

Initialized empty Git repository in /content/.git/
remote: Enumerating objects: 104, done.
remote: Total 104 (delta 0), reused 0 (delta 0), pack-reused 104
Receiving objects: 100% (104/104), 17.31 MiB | 20.71 MiB/s, done.
Resolving deltas: 100% (41/41), done.
From https://github.com/LambdaSchool/DS-Unit-2-Regression-Classification
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master

In [0]:
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
# import numpy, pandas.
import numpy as np
import pandas as pd

In [0]:
# Read New York City apartment rental listing data
df = pd.read_csv('../data/renthop-nyc.csv')
assert df.shape == (49352, 34)
# Remove the most extreme 1% prices,
# the most extreme .1% latitudes, &
# the most extreme .1% longitudes
df = df[(df['price'] >= np.percentile(df['price'], 0.5)) & 
        (df['price'] <= np.percentile(df['price'], 99.5)) & 
        (df['latitude'] >= np.percentile(df['latitude'], 0.05)) & 
        (df['latitude'] < np.percentile(df['latitude'], 99.95)) &
        (df['longitude'] >= np.percentile(df['longitude'], 0.05)) & 
        (df['longitude'] <= np.percentile(df['longitude'], 99.95))]

In [8]:
# show the data frame with headers.
df.head()

   bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0
2        1.0         1  ...                 0                    0
3        1.0         1  ...                 0                    0
4        1.0         4  ...                 0                    0

[5 rows x 34 columns]

In [0]:
# use datetaime on 'created' column.
df['created'] = pd.to_datetime(df['created'])
# set index on 'created'.
df = df.set_index(df['created'])
# sort the inex 'created' column.
df = df.sort_index()

In [11]:
# created the train data 4/1 to 5/31.
dftrain = df['2016-04-01':'2016-05-31']
# create the test data 6/1 to 6/30.
dftest  = df['2016-06-01':'2016-06-30']
# show the shape of both data frames.
print("Train Dataset 'April 2016 + May 2016':",dftrain.shape)
print("Test Dataset'June 2016':",dftest.shape)

Train Dataset 'April 2016 + May 2016': (31844, 34)
Test Dataset'June 2016': (16973, 34)

In [12]:
# show the train data frame with headers.
dftrain.head()

                     bathrooms  ...  common_outdoor_space
created                         ...
2016-04-01 22:12:41        1.0  ...                     0
2016-04-01 22:56:00        1.0  ...                     0
2016-04-01 22:57:15        2.0  ...                     1
2016-04-01 23:26:07        1.0  ...                     1
2016-04-02 00:48:13        1.0  ...                     0

[5 rows x 34 columns]

In [13]:
# show the teast data frame with headers.
dftest.head()

                     bathrooms  ...  common_outdoor_space
created                         ...
2016-06-01 01:10:37        1.0  ...                     0
2016-06-01 01:11:06        1.0  ...                     0
2016-06-01 01:11:12        1.0  ...                     0
2016-06-01 01:11:52        1.0  ...                     0
2016-06-01 01:12:22        1.0  ...                     0

[5 rows x 34 columns]

## Bedrooms and Bathrooms Features.

### Linear Regression.

In [0]:
# import LinearRegression from sklearn.linear_model.
from sklearn.linear_model import LinearRegression

In [15]:
# label and create LinearRegression() model for train data.
model = LinearRegression()
# set all the features from the data set we want to use.
features = ['bedrooms', 'bathrooms']
# set the target to 'price'.
target = 'price'
# set the 'features' data to X.
X = dftrain[features]
# set the 'target' data to Y.
y = dftrain[target]
# .fit the X and Y data to the model.
model.fit(X, y)
# label and create them model.predict(X).
y_pred = model.predict(X)

####

# label and create LinearRegression() model for test data.
model1 = LinearRegression()
# set all the features from the data set we want to use.
features1 = ['bedrooms', 'bathrooms']
# set the target to 'price'.
target1 = 'price'
# set the 'features' data to X1.
X1 = dftest[features1]
# set the 'target' data to Y1.
y1 = dftest[target1]
# .fit the X1 and Y1 data to the model.
model1.fit(X1, y1)
# label and create them model.predict(X1).
y_pred1 = model1.predict(X1)
# show the results.
print("(train data) 2 bedroom 2 bathrooms 'predicted' price =", model.predict(np.array([[2, 2]])))
print("(train data) 2 bedroom 1 bathrooms 'predicted' price =", model.predict(np.array([[2, 1]])))
print("(train data) intercept =", model.intercept_)
print("(train data) coefficient =", model.coef_)
print("(test data) 2 bedroom 2 bathrooms 'predicted' price =", model1.predict(np.array([[2, 2]])))
print("(test data) 2 bedroom 1 bathrooms 'predicted' price =", model1.predict(np.array([[2, 1]])))
print("(test data) intercept =", model1.intercept_)
print("(test data) coefficient =", model1.coef_)

(train data) 2 bedroom 2 bathrooms 'predicted' price = [5409.5887146]
(train data) 2 bedroom 1 bathrooms 'predicted' price = [3336.97859821]
(train data) intercept = 485.7186900232223
(train data) coefficient = [ 389.3248959  2072.61011639]
(test data) 2 bedroom 2 bathrooms 'predicted' price = [5479.43665375]
(test data) 2 bedroom 1 bathrooms 'predicted' price = [3329.18928321]
(test data) intercept = 425.08559409771306
(test data) coefficient = [ 376.92815928 2150.24737055]

### RMSE, MAE, and $R^2$.

In [0]:
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import mean_absolute_error, r2_score

In [17]:
rms = sqrt(mean_squared_error(y, y_pred))
mae = mean_absolute_error(y, y_pred)
r2 = r2_score(y, y_pred)
rms1 = sqrt(mean_squared_error(y1, y_pred1))
mae1 = mean_absolute_error(y1, y_pred1)
r21 = r2_score(y1, y_pred1)
print("(train data) root mean square error =", rms)
print("(train data)  mean absolute error =", mae)
print("(train data)  R2 score =", r2)
print("(test data) root mean square error =", rms1)
print("(test data)  mean absolute error =", mae1)
print("(test data)  R2 score =", r21)

(train data) root mean square error = 1232.0225917223484
(train data)  mean absolute error = 818.5310213271715
(train data)  R2 score = 0.5111543084316608
(test data) root mean square error = 1219.2441640676209
(test data)  mean absolute error = 828.1524829496833
(test data)  R2 score = 0.5217032949584466

## Bathrooms and Outdoor Space.

### Linear Regression.

In [18]:
# label and create LinearRegression() model for train data.
model = LinearRegression()
# set all the features from the data set we want to use.
features = ['bathrooms', 'outdoor_space']
# set the target to 'price'.
target = 'price'
# set the 'features' data to X.
X = dftrain[features]
# set the 'target' data to Y.
y = dftrain[target]
# .fit the X and Y data to the model.
model.fit(X, y)
# label and create them model.predict(X).
y_pred = model.predict(X)

####

# label and create LinearRegression() model for test data.
model1 = LinearRegression()
# set all the features from the data set we want to use.
features1 = ['bathrooms', 'outdoor_space']
# set the target to 'price'.
target1 = 'price'
# set the 'features' data to X1.
X1 = dftest[features1]
# set the 'target' data to Y1.
y1 = dftest[target1]
# .fit the X1 and Y1 data to the model.
model1.fit(X1, y1)
# label and create them model.predict(X1).
y_pred1 = model1.predict(X1)
# show the results.
print("(train data) 2 bathrooms with outdoor space 'predicted' price =", model.predict(np.array([[2, 1]])))
print("(train data) 2 bathrooms no outdoor space 'predicted' price =", model.predict(np.array([[2, 0]])))
print("(train data) intercept =", model.intercept_)
print("(train data) coefficient =", model.coef_)
print("(test data) 2 bathrooms with outdoor space 'predicted' price =", model1.predict(np.array([[2, 1]])))
print("(test data) 2 bathrooms no outdoor space 'predicted' price =", model1.predict(np.array([[2, 0]])))
print("(test data) intercept =", model1.intercept_)
print("(test data) coefficient =", model1.coef_)

(train data) 2 bathrooms with outdoor space 'predicted' price = [5781.14842185]
(train data) 2 bathrooms no outdoor space 'predicted' price = [5557.2243596]
(train data) intercept = 499.00178687940434
(train data) coefficient = [2529.11128636  223.92406225]
(test data) 2 bathrooms with outdoor space 'predicted' price = [5858.69454263]
(test data) 2 bathrooms no outdoor space 'predicted' price = [5634.70460131]
(test data) intercept = 455.8156839112198
(test data) coefficient = [2589.4444587   223.98994131]

### RMSE, MAE, and $R^2$.

In [19]:
rms = sqrt(mean_squared_error(y, y_pred))
mae = mean_absolute_error(y, y_pred)
r2 = r2_score(y, y_pred)
rms1 = sqrt(mean_squared_error(y1, y_pred1))
mae1 = mean_absolute_error(y1, y_pred1)
r21 = r2_score(y1, y_pred1)
print("(train data) root mean square error =", rms)
print("(train data)  mean absolute error =", mae)
print("(train data)  R2 score =", r2)
print("(test data) root mean square error =", rms1)
print("(test data)  mean absolute error =", mae1)
print("(test data)  R2 score =", r21)

(train data) root mean square error = 1282.8381505969444
(train data)  mean absolute error = 884.1048784575621
(train data)  R2 score = 0.4699971771127297
(test data) root mean square error = 1268.154572190475
(test data)  mean absolute error = 889.5578798116944
(test data)  R2 score = 0.4825595192664889

## Longitude and Latitude Space.

### Linear Regression.

In [21]:
# label and create LinearRegression() model for train data.
model = LinearRegression()
# set all the features from the data set we want to use.
features = ['longitude', 'latitude']
# set the target to 'price'.
target = 'price'
# set the 'features' data to X.
X = dftrain[features]
# set the 'target' data to Y.
y = dftrain[target]
# .fit the X and Y data to the model.
model.fit(X, y)
# label and create them model.predict(X).
y_pred = model.predict(X)

####

# label and create LinearRegression() model for test data.
model1 = LinearRegression()
# set all the features from the data set we want to use.
features1 = ['longitude', 'latitude']
# set the target to 'price'.
target1 = 'price'
# set the 'features' data to X1.
X1 = dftest[features1]
# set the 'target' data to Y1.
y1 = dftest[target1]
# .fit the X1 and Y1 data to the model.
model1.fit(X1, y1)
# label and create them model.predict(X1).
y_pred1 = model1.predict(X1)
# show the results.
print("(train data) 2 bathrooms with outdoor space 'predicted' price =", model.predict(np.array([[2, 1]])))
print("(train data) 2 bathrooms no outdoor space 'predicted' price =", model.predict(np.array([[2, 0]])))
print("(train data) intercept =", model.intercept_)
print("(train data) coefficient =", model.coef_)
print("(test data) 2 bathrooms with outdoor space 'predicted' price =", model1.predict(np.array([[2, 1]])))
print("(test data) 2 bathrooms no outdoor space 'predicted' price =", model1.predict(np.array([[2, 0]])))
print("(test data) intercept =", model1.intercept_)
print("(test data) coefficient =", model1.coef_)

(train data) 2 bathrooms with outdoor space 'predicted' price = [-1316155.20627438]
(train data) 2 bathrooms no outdoor space 'predicted' price = [-1318363.39599334]
(train data) intercept = -1285931.985165547
(train data) coefficient = [-16215.70541389   2208.18971896]
(test data) 2 bathrooms with outdoor space 'predicted' price = [-1364009.41961739]
(test data) 2 bathrooms no outdoor space 'predicted' price = [-1366620.11739489]
(test data) intercept = -1333349.7055827554
(test data) coefficient = [-16635.20590607   2610.6977775 ]

### RMSE, MAE, and $R^2$.

In [22]:
rms = sqrt(mean_squared_error(y, y_pred))
mae = mean_absolute_error(y, y_pred)
r2 = r2_score(y, y_pred)
rms1 = sqrt(mean_squared_error(y1, y_pred1))
mae1 = mean_absolute_error(y1, y_pred1)
r21 = r2_score(y1, y_pred1)
print("(train data) root mean square error =", rms)
print("(train data)  mean absolute error =", mae)
print("(train data)  R2 score =", r2)
print("(test data) root mean square error =", rms1)
print("(test data)  mean absolute error =", mae1)
print("(test data)  R2 score =", r21)

(train data) root mean square error = 1704.2079552598761
(train data)  mean absolute error = 1147.1493278231212
(train data)  R2 score = 0.06463820907125295
(test data) root mean square error = 1702.9223680796963
(test data)  mean absolute error = 1145.2534320943037
(test data)  R2 score = 0.06694827937588999

## Elevator and Common Outdoor Space.

### linear Regression.

In [24]:
# label and create LinearRegression() model for train data.
model = LinearRegression()
# set all the features from the data set we want to use.
features = ['elevator', 'common_outdoor_space']
# set the target to 'price'.
target = 'price'
# set the 'features' data to X.
X = dftrain[features]
# set the 'target' data to Y.
y = dftrain[target]
# .fit the X and Y data to the model.
model.fit(X, y)
# label and create them model.predict(X).
y_pred = model.predict(X)

####

# label and create LinearRegression() model for test data.
model1 = LinearRegression()
# set all the features from the data set we want to use.
features1 = ['elevator', 'common_outdoor_space']
# set the target to 'price'.
target1 = 'price'
# set the 'features' data to X1.
X1 = dftest[features1]
# set the 'target' data to Y1.
y1 = dftest[target1]
# .fit the X1 and Y1 data to the model.
model1.fit(X1, y1)
# label and create them model.predict(X1).
y_pred1 = model1.predict(X1)
# show the results.
print("(train data) 2 bathrooms with outdoor space 'predicted' price =", model.predict(np.array([[2, 1]])))
print("(train data) 2 bathrooms no outdoor space 'predicted' price =", model.predict(np.array([[2, 0]])))
print("(train data) intercept =", model.intercept_)
print("(train data) coefficient =", model.coef_)
print("(test data) 2 bathrooms with outdoor space 'predicted' price =", model1.predict(np.array([[2, 1]])))
print("(test data) 2 bathrooms no outdoor space 'predicted' price =", model1.predict(np.array([[2, 0]])))
print("(test data) intercept =", model1.intercept_)
print("(test data) coefficient =", model1.coef_)

(train data) 2 bathrooms with outdoor space 'predicted' price = [4453.76931925]
(train data) 2 bathrooms no outdoor space 'predicted' price = [4655.09311728]
(train data) intercept = 3193.929935303338
(train data) coefficient = [ 730.58159099 -201.32379803]
(test data) 2 bathrooms with outdoor space 'predicted' price = [4732.21365166]
(test data) 2 bathrooms no outdoor space 'predicted' price = [4697.25442682]
(test data) intercept = 3201.706689631647
(test data) coefficient = [747.7738686   34.95922484]

### RMSE, MAE, and $R^2$.

In [25]:
rms = sqrt(mean_squared_error(y, y_pred))
mae = mean_absolute_error(y, y_pred)
r2 = r2_score(y, y_pred)
rms1 = sqrt(mean_squared_error(y1, y_pred1))
mae1 = mean_absolute_error(y1, y_pred1)
r21 = r2_score(y1, y_pred1)
print("(train data) root mean square error =", rms)
print("(train data)  mean absolute error =", mae)
print("(train data)  R2 score =", r2)
print("(test data) root mean square error =", rms1)
print("(test data)  mean absolute error =", mae1)
print("(test data)  R2 score =", r21)

(train data) root mean square error = 1724.5217237580869
(train data)  mean absolute error = 1174.3449736441487
(train data)  R2 score = 0.042206715360120994
(test data) root mean square error = 1722.7758600514044
(test data)  mean absolute error = 1170.2212883958011
(test data)  R2 score = 0.0450655229825635